<?php
$noSharedBg = true;
require_once APP_ROOT . '/includes/bg_seabed.php';
$extraHead = $bgSeabedHead . '<style>
.hero-canvas-wrap{position:relative;min-height:0;overflow:hidden;background:radial-gradient(circle at center, #0a2342 0%, #020813 100%);padding-bottom:0}
.hero-canvas-wrap .after-canvas{position:relative;z-index:2}
.hero{min-height:auto;display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:2rem;padding:1.6rem 2rem 1.6rem 3rem;position:relative;overflow:hidden;border-bottom:1px solid var(--border)}
.hero-content{position:relative;z-index:1}.hero-tag{display:inline-flex;align-items:center;gap:6px;background:rgba(45,212,191,0.12);border:1px solid rgba(45,212,191,0.3);color:var(--brand-light);padding:5px 14px;border-radius:30px;font-size:.75rem;font-weight:600;letter-spacing:1px;text-transform:uppercase;margin-bottom:1.5rem}
.hero-title{font-family:var(--font-display);font-size:clamp(2rem,4.2vw,3.1rem);line-height:1.2;margin-bottom:.75rem}.hero-title span{color:var(--brand-light)}.hero-title .amber{color:var(--amber-light)}
.hero-desc{color:var(--muted);font-size:.95rem;line-height:1.55;margin-bottom:1.5rem;max-width:430px}.hero-actions{display:flex;gap:1rem;flex-wrap:wrap}
.hero-visual{display:grid;grid-template-columns:1fr 1fr;gap:1rem;width:800px}
.hero-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:1.5rem 1.8rem;display:flex;align-items:center;gap:1.2rem;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);box-shadow:0 10px 30px rgba(0,0,0,0.2);will-change:transform;transform:translate3d(0,0,0);animation:cardFloatSmooth 7s cubic-bezier(0.445,0.05,0.55,0.95) infinite}
.hero-card:nth-child(1){animation-delay:0s}.hero-card:nth-child(2){animation-delay:1.5s}.hero-card:nth-child(3){animation-delay:3s}.hero-card:nth-child(4){animation-delay:4.5s}.hero-card:nth-child(5){animation-delay:6s}.hero-card:nth-child(6){animation-delay:7.5s}
.hero-card:hover{border-color:rgba(79,195,247,0.35);background:rgba(255,255,255,0.08);transform:translate3d(0,-4px,0) scale(1.02)!important;transition:transform 0.3s cubic-bezier(0.25,1,0.5,1),border-color 0.3s ease,background 0.3s ease}
@keyframes cardFloatSmooth{0%,100%{transform:translate3d(0,0,0)}50%{transform:translate3d(0,-14px,0)}}
.hc-icon{width:44px;height:44px;background:linear-gradient(135deg,var(--brand),var(--brand-dark));border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:1.35rem}
.hc-title{font-weight:700;font-size:.95rem;color:#4fc3f7;margin-bottom:2px}
.hc-sub{font-size:.75rem;color:var(--muted);line-height:1.3}
.stats-band{border-bottom:1px solid var(--border);background:rgba(10,14,26,0.5);padding:1.5rem 0}.stats-inner{max-width:1200px;margin:0 auto;padding:0 1.5rem;display:flex;justify-content:space-around;gap:1rem;flex-wrap:wrap}.stat-item{text-align:center;min-width:125px}.stat-num{font-size:clamp(1.6rem,2.5vw,2.1rem);font-weight:800;color:var(--brand-light)}.stat-label{font-size:.7rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);margin-top:.45rem}
.categories-strip{display:flex;gap:.75rem;overflow-x:auto;padding:.3rem 0}.cat-pill{display:inline-flex;align-items:center;gap:6px;padding:.45rem .95rem;background:var(--surface);border:1px solid var(--border);border-radius:30px;white-space:nowrap;font-size:.8rem;font-weight:600;color:var(--muted);text-decoration:none}.cat-pill.active,.cat-pill:hover{background:rgba(45,212,191,0.12);border-color:rgba(45,212,191,0.3);color:var(--brand-light)}
.product-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:1rem}.section-header{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:1.2rem}.section-title{font-family:var(--font-display);font-size:1.45rem}.section-title span{color:var(--brand-light)}.section-sub{color:var(--muted);font-size:.82rem}
.steps-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem}.step-card{text-align:center;padding:1.5rem 1rem;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);will-change:transform;transform:translate3d(0,0,0);animation:cardFloatSmooth 7s cubic-bezier(0.445,0.05,0.55,0.95) infinite}
.step-card:nth-child(1){animation-delay:0s}.step-card:nth-child(2){animation-delay:0.8s}.step-card:nth-child(3){animation-delay:1.6s}.step-card:nth-child(4){animation-delay:2.4s}.step-number{width:24px;height:24px;background:linear-gradient(135deg,var(--brand),var(--brand-dark));color:#081225;border-radius:50%;font-size:.68rem;font-weight:800;display:flex;align-items:center;justify-content:center;margin:0 auto .8rem}.step-icon{font-size:2rem;margin-bottom:.7rem}.step-title{font-weight:700;font-size:.9rem;margin-bottom:.35rem}.step-desc{font-size:.78rem;color:var(--muted);line-height:1.45}
.cta-banner{background:linear-gradient(135deg,rgba(13,148,136,0.3),rgba(45,212,191,0.1));border:1px solid rgba(45,212,191,0.2);border-radius:var(--radius);padding:2.1rem 2.3rem;display:flex;align-items:center;justify-content:space-between;gap:2rem}.cta-title{font-family:var(--font-display);font-size:1.45rem}.cta-desc{color:var(--muted);margin-top:.45rem;font-size:.84rem}
@media (max-width:768px){.hero{grid-template-columns:1fr;padding:2rem 1.25rem}.hero-visual{display:none}.steps-grid{grid-template-columns:1fr 1fr}.cta-banner{flex-direction:column;text-align:center;padding:2rem}}
</style>';
$extraScripts = $bgSeabedScripts; ?>
<div class="hero-canvas-wrap">
    <canvas id="seabed-canvas"></canvas>
    <section class="hero" style="position:relative;z-index:2;">
      <div class="hero-content">
        <div class="hero-tag">Boat Catch Inventory Sync</div>
        <h1 class="hero-title"><span>Fish Market</span><br>Live Catch Stock<br><span class="amber">From Port to Storefront</span></h1>
        <p class="hero-desc">Fishing boats land their daily catch at the port, where it is recorded into inventory. Fish Market displays that live stock volume so customers can see exactly what is available right now.</p>
        <div class="hero-actions">
          <a href="<?= url_for('shop') ?>" class="btn btn-primary btn-lg">Shop Now</a>
          <?php if (!isFmLoggedIn()): ?><a href="<?= url_for('register') ?>" class="btn btn-outline btn-lg">Create Account</a><?php endif; ?>
        </div>
      </div>
      <div class="hero-visual">
        <div class="hero-card"><div class="hc-icon">🐟</div><div><div class="hc-title">Boat Catch Intake</div><div class="hc-sub">Catch landed and registered at port</div></div></div>
        <div class="hero-card"><div class="hc-icon">🦐</div><div><div class="hc-title">Live Stock Visibility</div><div class="hc-sub">Current available quantity shown in store</div></div></div>
        <div class="hero-card"><div class="hc-icon">🚚</div><div><div class="hc-title">Order Routing</div><div class="hc-sub">Orders are sent back to port operations</div></div></div>
        <div class="hero-card"><div class="hc-icon">⛵</div><div><div class="hc-title">Fleet Tracking</div><div class="hc-sub">Real-time vessel monitoring and fishing zones</div></div></div>
        <div class="hero-card"><div class="hc-icon">💰</div><div><div class="hc-title">Smart Pricing</div><div class="hc-sub">Dynamic market pricing based on catch volume</div></div></div>
        <div class="hero-card"><div class="hc-icon">❄️</div><div><div class="hc-title">Cold Chain</div><div class="hc-sub">Temperature-controlled storage from sea to store</div></div></div>
      </div>
    </section>
  </div>
<div class="stats-band"><div class="stats-inner"><div class="stat-item"><div class="stat-num">500+</div><div class="stat-label">Registered Users</div></div><div class="stat-item"><div class="stat-num"><?= count($allProducts ?? products()) ?></div><div class="stat-label">Products</div></div><div class="stat-item"><div class="stat-num">1000+</div><div class="stat-label">Successful Orders</div></div><div class="stat-item"><div class="stat-num">4.9★</div><div class="stat-label">User Rating</div></div></div></div>
<section class="section" style="padding-top: 2.5rem"><div class="container"><div class="section-header"><div><h2 class="section-title"><span>Featured</span> Products</h2><p class="section-sub">Our freshest and most popular picks today</p></div><a href="<?= url_for('shop') ?>" class="btn btn-outline btn-sm">View All →</a></div><div class="product-grid"><?php foreach ($featured as $product): ?><a href="<?= url_for('product', ['slug' => $product['slug']]) ?>" class="product-card"><?php if ($product['is_featured']): ?><div class="featured-badge">Featured</div><?php endif; ?><?php if ($product['image']): ?><img src="<?= e(product_image($product['image'])) ?>" alt="<?= e($product['name']) ?>" class="product-card-img"><?php else: ?><div class="product-card-img">🐟</div><?php endif; ?><div class="product-card-body"><div class="product-card-cat"><?= e($product['category_name']) ?></div><div class="product-card-name"><?= e($product['name']) ?></div><div><span class="product-card-price">RM <?= e(formatted_money((float) $product['price'])) ?></span><span class="product-card-unit">/<?= e($product['unit']) ?> (3kg start)</span></div><div class="product-card-stock" style="<?php $hs = (int)$product['stock']; 
  if ($hs <= 0): ?>display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;background:rgba(239,68,68,0.15);color:#ef4444<?php elseif ($hs <= 10): ?>display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;background:rgba(217,119,6,0.15);color:#fbbf24<?php else: ?>display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;background:rgba(52,211,153,0.15);color:var(--ok)<?php endif; ?>"><?php if ($hs <= 0): ?>✕ Out of Stock<?php elseif ($hs <= 10): ?>⚠️ Only <?= $hs ?> Units left<?php else: ?>✓ In Stock<?php endif; ?></div></div></a><?php endforeach; ?></div></div></section>
<section class="section" style="border-top:1px solid var(--border);border-bottom:1px solid var(--border)"><div class="container"><div style="text-align:center;margin-bottom:2.5rem"><h2 class="section-title">How to <span>Shop</span></h2><p class="section-sub">Four simple steps to fresh delivery</p></div><div class="steps-grid"><div class="step-card"><div class="step-number">1</div><div class="step-icon">🔍</div><div class="step-title">Browse Products</div><div class="step-desc">Explore our curated selection of fresh seafood, filter by category</div></div><div class="step-card"><div class="step-number">2</div><div class="step-icon">🧺</div><div class="step-title">Add to Cart</div><div class="step-desc">Add your favourite items to cart and adjust quantities anytime</div></div><div class="step-card"><div class="step-number">3</div><div class="step-icon">💳</div><div class="step-title">Wallet Payment</div><div class="step-desc">Pay quickly and securely using your e-wallet balance</div></div><div class="step-card"><div class="step-number">4</div><div class="step-icon">🚚</div><div class="step-title">Home Delivery</div><div class="step-desc">We deliver fresh the same day, ensuring quality at your door</div></div></div></div></section>
<section class="section"><div class="container"><div class="section-header"><div><h2 class="section-title">Just <span>Arrived</span></h2><p class="section-sub">Freshly landed catches from returning vessels</p></div></div><?php if (!empty($latest)): ?><div class="product-grid"><?php foreach ($latest as $product): ?><a href="<?= url_for('product', ['slug' => $product['slug']]) ?>" class="product-card"><?php if ($product['image']): ?><img src="<?= e(product_image($product['image'])) ?>" alt="<?= e($product['name']) ?>" class="product-card-img"><?php else: ?><div class="product-card-img">🐟</div><?php endif; ?><div class="product-card-body"><div style="display:inline-block;padding:1px 8px;border-radius:20px;font-size:10px;font-weight:700;background:rgba(14,165,233,0.15);color:#0ea5e9;margin-bottom:4px">🐟 Fresh Catch</div><div class="product-card-name"><?= e($product['name']) ?></div><div><span class="product-card-price">RM <?= e(formatted_money((float) $product['price'])) ?></span><span class="product-card-unit">/<?= e($product['unit']) ?> (3kg start)</span></div><div style="font-size:.7rem;margin-top:4px;display:flex;align-items:center;gap:6px;flex-wrap:wrap"><?php $lt = $product['landed_at'] ?? ''; if ($lt): $ts = strtotime($lt); $isToday = date('Y-m-d') === date('Y-m-d', $ts); ?><span style="display:inline-block;padding:1px 8px;border-radius:12px;font-size:9px;font-weight:700;background:<?= $isToday ? 'rgba(52,211,153,0.2);color:#34d399' : 'rgba(148,163,184,0.2);color:#94a3b8' ?>"><?= $isToday ? 'Today' : date('d M', $ts) ?></span><?php endif; ?><?php if (!empty($product['vessel_name'])): ?><span style="color:var(--muted);font-size:9px">⛵ <?= e($product['vessel_name']) ?></span><?php endif; ?><?php if (!empty($product['trip_id'])): ?><span style="color:var(--muted);font-size:9px">#<?= (int)$product['trip_id'] ?></span><?php endif; ?></div></div></a><?php endforeach; ?></div><?php else: ?><div style="text-align:center;padding:40px 20px;color:var(--muted);"><p style="font-size:.9rem">No vessels have returned with catch yet.</p><p style="font-size:.75rem;margin-top:6px">Products appear here when fishing trips complete unloading at port.</p></div><?php endif; ?></div></section>
<?php if (!isFmLoggedIn()): ?>
<section class="section" style="padding-top:0"><div class="container"><div class="cta-banner"><div><h2 class="cta-title">Sign Up and Start Shopping!</h2><p class="cta-desc">Create an account to manage orders and pay easily with your e-wallet</p></div><div style="display:flex;gap:1rem;flex-wrap:wrap"><a href="<?= url_for('register') ?>" class="btn btn-amber btn-lg">Sign Up Now</a><a href="<?= url_for('login') ?>" class="btn btn-outline">Already have an account</a></div></div></div></section>
<?php endif; ?>
