<?php $extraHead = '<style>
.shop-layout{display:grid;grid-template-columns:240px 1fr;gap:2rem}.sidebar{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:1.5rem;height:fit-content;position:sticky;top:80px}.sidebar h3{font-size:.85rem;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--muted);margin-bottom:1rem}
.sidebar-link{display:flex;align-items:center;gap:8px;padding:.55rem .75rem;border-radius:var(--radius-sm);color:var(--text);text-decoration:none;font-size:.9rem;font-weight:500;margin-bottom:2px}.sidebar-link.active,.sidebar-link:hover{background:rgba(45,212,191,0.08);color:var(--brand)}
.shop-toolbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.5rem;gap:1rem;flex-wrap:wrap}.search-bar{display:flex;gap:.5rem;flex:1;max-width:400px}.search-bar input,.sort-select{padding:.6rem 1rem;border:1px solid var(--border);border-radius:var(--radius-sm);background:rgba(10,14,26,0.4);color:var(--text)}
.product-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:1.2rem}.empty-state{text-align:center;padding:4rem 2rem;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius)}
.product-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);overflow:hidden;transition:.15s;text-decoration:none;color:inherit;display:block}.product-card:hover{border-color:var(--brand);box-shadow:0 4px 20px rgba(0,0,0,.3)}
.product-card-img{width:100%;aspect-ratio:4/3;object-fit:cover;display:flex;align-items:center;justify-content:center;background:rgba(255,255,255,0.03);font-size:3rem}
.product-card-body{padding:1rem}
.product-card-cat{font-size:.72rem;text-transform:uppercase;letter-spacing:1px;color:var(--muted);font-weight:700;margin-bottom:.2rem}
.product-card-name{font-weight:700;font-size:1rem;margin-bottom:.5rem}
.product-card-price{font-weight:800;font-size:1.2rem;color:var(--amber-light)}
.product-card-unit{font-size:.78rem;color:var(--muted);font-weight:400}
.product-card-stock{font-size:.78rem;margin-top:.3rem}
@media (max-width:768px){.shop-layout{grid-template-columns:1fr}.sidebar{position:static}}
</style>'; ?>
<div class="page-header"><div class="container"><h1>🛒 Fish Market</h1><p>Fresh fish and seafood only</p></div></div>
<div class="container"><div class="shop-layout"><aside class="sidebar"><h3>🗂 Fish Categories</h3><a href="<?= url_for('shop', ['q' => $search, 'sort' => $sort]) ?>" class="sidebar-link <?= $selectedCategory ? '' : 'active' ?>">🌟 All Seafood</a><?php foreach ($categories as $cat): ?><a href="<?= url_for('shop', ['category' => $cat['slug'], 'q' => $search, 'sort' => $sort]) ?>" class="sidebar-link <?= $selectedCategory === $cat['slug'] ? 'active' : '' ?>"><?= e($cat['name']) ?></a><?php endforeach; ?></aside><div><div class="shop-toolbar"><form method="get" class="search-bar"><input type="hidden" name="page" value="shop"><?php if ($selectedCategory): ?><input type="hidden" name="category" value="<?= e($selectedCategory) ?>"><?php endif; ?><?php if ($sort): ?><input type="hidden" name="sort" value="<?= e($sort) ?>"><?php endif; ?><input type="text" name="q" value="<?= e($search) ?>" placeholder="Search products..."><button type="submit" class="btn btn-primary btn-sm">🔍</button></form><div style="display:flex;align-items:center;gap:1rem"><span style="font-size:.85rem;color:var(--muted)"><?= count($productsList) ?> products found</span><select class="sort-select" onchange="location.href=this.value"><option value="<?= url_for('shop', array_filter(['category' => $selectedCategory, 'q' => $search])) ?>">Default Sort</option><option value="<?= url_for('shop', array_filter(['category' => $selectedCategory, 'q' => $search, 'sort' => 'price_asc'])) ?>" <?= $sort === 'price_asc' ? 'selected' : '' ?>>Price: Low to High</option><option value="<?= url_for('shop', array_filter(['category' => $selectedCategory, 'q' => $search, 'sort' => 'price_desc'])) ?>" <?= $sort === 'price_desc' ? 'selected' : '' ?>>Price: High to Low</option><option value="<?= url_for('shop', array_filter(['category' => $selectedCategory, 'q' => $search, 'sort' => 'newest'])) ?>" <?= $sort === 'newest' ? 'selected' : '' ?>>Newest First</option></select></div></div><?php if ($productsList): ?><div class="product-grid"><?php foreach ($productsList as $product): ?><a href="<?= url_for('product', ['slug' => $product['slug']]) ?>" class="product-card"><?php if ($product['image']): ?><img src="<?= e(product_image($product['image'])) ?>" alt="<?= e($product['name']) ?>" class="product-card-img"><?php else: ?><div class="product-card-img">🐟</div><?php endif; ?><div class="product-card-body"><div class="product-card-cat"><?= e($product['category_name']) ?></div><div class="product-card-name"><?= e($product['name']) ?></div><div><span class="product-card-price">RM <?= e(formatted_money((float) $product['price'])) ?></span><span class="product-card-unit"> / <?= e($product['unit']) ?> (3kg start)</span></div><div class="product-card-stock" style="<?php $ts = (int)$product['stock']; 
  if ($ts <= 0): ?>display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;background:rgba(239,68,68,0.15);color:#ef4444<?php elseif ($ts <= 10): ?>display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;background:rgba(217,119,6,0.15);color:#fbbf24<?php else: ?>display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;background:rgba(52,211,153,0.15);color:var(--ok)<?php endif; ?>"><?php 
  if ($ts <= 0): ?>✕ Out of Stock<?php elseif ($ts <= 10): ?>⚠️ Only <?= $ts ?> Units left<?php else: ?>✓ In Stock<?php endif; ?></div></div></a><?php endforeach; ?></div><?php else: ?><div class="empty-state"><div style="font-size:4rem;margin-bottom:1rem">🔍</div><h3>No products found</h3><p style="color:var(--muted)">Try different keywords or browse another category</p></div><?php endif; ?></div></div></div>
